# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: fix-encoding-pragma
    -   id: name-tests-test

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8

-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
        - id: mypy
          additional_dependencies: [pydantic]

-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
        - id: autoflake
