# This is a basic workflow to help you get started with Actions
name: run_docs
# Run on push and pull request for all branches
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially
# or in parallel
jobs:
  # This workflow contains a single job called "docs"
  docs:
    # The type of runner that the job will run on
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    #----------------------------------------------
    # Set python environment
    #----------------------------------------------
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    #----------------------------------------------
    # install poetry
    #----------------------------------------------
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    #----------------------------------------------
    # install dependencies
    #----------------------------------------------
    - name: Install dependencies
      run: poetry install --no-interaction

    #----------------------------------------------
    # Runs precommit using the repo config file
    #----------------------------------------------
    - name: Build Documentation
      run: |
        poetry run sphinx-apidoc -f -o docs/source hippo --implicit-namespaces
        poetry run sphinx-build -c docs/source -b html docs/source docs/build/html
