# This is a basic workflow to help you get started with Actions
name: run_tests
# Run on push and pull request for all branches
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially
# or in parallel
jobs:
  # This workflow contains a single job called "pytest"
  tests:
    # The type of runner that the job will run on
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    #----------------------------------------------
    # Set python environment
    #----------------------------------------------
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    #----------------------------------------------
    # install poetry
    #----------------------------------------------
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    #----------------------------------------------
    # install dependencies
    #----------------------------------------------
    - name: Install dependencies
      run: poetry install --no-interaction

    #----------------------------------------------
    # Runs to check test coverage > 90%
    #----------------------------------------------
    - name: Erase Coverage And Run Tests
      run: |
        poetry run coverage erase
        poetry run coverage run -m pytest -v -s

    - name: Check Coverage Percentage
      run: |
        poetry run coverage report -m
        poetry run coverage json
        jq -e '.totals.percent_covered > 90' coverage.json
